name = "WallpaperGroups"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["WallpaperGroups"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.26.0"

# Documentation generation
[[require]]
name = "doc-gen4"
scope = "leanprover"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"

[[lean_lib]]
name = "WallpaperGroups"
